# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c7379629ba00ce89aa40e130199d65a4ee78fe283f335fdb3367bc4e71735e366de376ff7ac3c0638900e3a652ebbcf6722e6a3069dd7ad072a61b1718ad2a2

test:
  secret_key_base: 136cae8e6e71e687f248eabf6abea900fff536fe66080202a6b74f37d07ba60bef54c3075c64e3733698502da4eca23aa9c7a2572f24b9f9d6c65c46ec9e390b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
